# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpptnm <- function(sigma, a, mu, sig, ssig, low, high) {
    .Call('CNTTN_rcpptnm', PACKAGE = 'CNTTN', sigma, a, mu, sig, ssig, low, high)
}

rcppcomdel <- function(W, U, H) {
    .Call('CNTTN_rcppcomdel', PACKAGE = 'CNTTN', W, U, H)
}

rcppng <- function(sigma, sigw, isigt, invL, muW, rngN) {
    .Call('CNTTN_rcppng', PACKAGE = 'CNTTN', sigma, sigw, isigt, invL, muW, rngN)
}

